---
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set Build Permissions
        run: |
          mkdir $GITHUB_WORKSPACE/test/cdk.out
          chmod 777 $GITHUB_WORKSPACE/test/cdk.out --recursive
          chmod 777 $GITHUB_WORKSPACE/lambda --recursive

      - name: Deploy Typescript Stack
        run: cd test && make deploy DESTROY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Python Stack
        run: cd test-python && make deploy DESTROY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
