---
name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set Build Permissions
        run: |
          mkdir $GITHUB_WORKSPACE/test/cdk.out
          chmod 777 $GITHUB_WORKSPACE/test/cdk.out --recursive
          chmod 777 $GITHUB_WORKSPACE/lambda --recursive

      - name: Deploy
        uses: udondan/cdk-nodejs@v0.4.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SUBDIR: test
          args: make deploy

      - name: Destroy
        uses: udondan/cdk-nodejs@v0.4.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SUBDIR: test
          args: make DESTROY
